version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgresNT
      POSTGRES_PASSWORD: 1234578
      POSTGRES_DB: nt-api
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: nt-api 
    build:
      context: .
      dockerfile: Dockerfile 
    restart: always
    environment:
      JWT_SECRET: eqweqweqdsfsdfsdfds
      JWT_EXPIRATION_TIME: 3600
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgresNT
      DB_PASSWORD: 1234578
      DB_NAME: nt-api
    ports:
      - "3000:3000" 

volumes:
  db_data:
