version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: nt-bd
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nt-api
      POSTGRES_USER: postgresNT
      POSTGRES_PASSWORD: 1234578
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: